require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/species", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Species. As you add validations to Species, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    { name: "Tyrannosaurus", dinosaur_type: "carnivore" }
  }

  let(:invalid_attributes) {
    { name: "", dinosaur_type: "carnivore" }
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # SpeciesController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Species.create! valid_attributes
      get species_index_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      species = Species.create! valid_attributes
      get species_url(species), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Species" do
        expect {
          post species_index_url,
               params: { species: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Species, :count).by(1)
      end

      it "renders a JSON response with the new species" do
        post species_index_url,
             params: { species: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Species" do
        expect {
          post species_index_url,
               params: { species: invalid_attributes }, as: :json
        }.to change(Species, :count).by(0)
      end

      it "renders a JSON response with errors for the new species" do
        post species_index_url,
             params: { species: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        { name: "Tyrannosaurus Rex" }
      }

      it "updates the requested species" do
        species = Species.create! valid_attributes
        patch species_url(species),
              params: { species: new_attributes }, headers: valid_headers, as: :json
        species.reload
        expect(species.name).to eq(new_attributes[:name])
      end

      it "renders a JSON response with the species" do
        species = Species.create! valid_attributes
        patch species_url(species),
              params: { species: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the species" do
        species = Species.create! valid_attributes
        patch species_url(species),
              params: { species: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested species" do
      species = Species.create! valid_attributes
      expect {
        delete species_url(species), headers: valid_headers, as: :json
      }.to change(Species, :count).by(-1)
    end
  end
end
